### ISSUE TITLE
Error occurred using compile.sh in the example

### ISSUE THREAD

**Issue by RoySRose** [spring-projects-experimental/spring-graal-native#10]
There is a compile error in the example

I am trying to test kotlin graal native.
I found this example. 
https://github.com/spring-projects-experimental/spring-graal-native/tree/master/spring-graal-native-samples/kotlin-webmvc

But when I complied using compile.sh as instructed. It gave me an error as below

```text
Error: No instances of org.springframework.util.unit.DataSize are allowed in the image heap as this class should be initialized at image runtime.Object has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked.
Detailed message:
Trace:  object org.springframework.util.unit.DataUnit
        method org.springframework.util.unit.DataSize.determineDataUnit(String, DataUnit)
Call path from entry point to org.springframework.util.unit.DataSize.determineDataUnit(String, DataUnit): 
        at org.springframework.util.unit.DataSize.determineDataUnit(DataSize.java:192)
        at org.springframework.util.unit.DataSize.parse(DataSize.java:182)
        at org.springframework.boot.convert.StringToDataSizeConverter.convert(StringToDataSizeConverter.java:57)
        at org.springframework.boot.convert.StringToDataSizeConverter.convert(StringToDataSizeConverter.java:48)
        at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:41)
        at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:191)
        at org.springframework.boot.convert.DelimitedStringToCollectionConverter.lambda$convert$0(DelimitedStringToCollectionConverter.java:72)
        at org.springframework.boot.convert.DelimitedStringToCollectionConverter$$Lambda$513/1107588916.apply(Unknown Source)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.util.stream.SpinedBuffer.forEach(SpinedBuffer.java:246)
        at java.util.stream.SpinedBuffer.toString(SpinedBuffer.java:269)
        at java.lang.String.valueOf(String.java:2994)
        at java.lang.StringBuilder.append(StringBuilder.java:131)
        at com.oracle.svm.core.amd64.AMD64CPUFeatureAccess.verifyHostSupportsArchitecture(AMD64CPUFeatureAccess.java:179)
        at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:129)
        at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:186)
        at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

com.oracle.svm.core.util.UserError$UserException: No instances of org.springframework.util.unit.DataSize are allowed in the image heap as this class should be initialized at image runtime.Object has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked.
Detailed message:
Trace:  object org.springframework.util.unit.DataUnit
        method org.springframework.util.unit.DataSize.determineDataUnit(String, DataUnit)
Call path from entry point to org.springframework.util.unit.DataSize.determineDataUnit(String, DataUnit): 
        at org.springframework.util.unit.DataSize.determineDataUnit(DataSize.java:192)
        at org.springframework.util.unit.DataSize.parse(DataSize.java:182)
        at org.springframework.boot.convert.StringToDataSizeConverter.convert(StringToDataSizeConverter.java:57)
        at org.springframework.boot.convert.StringToDataSizeConverter.convert(StringToDataSizeConverter.java:48)
        at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:41)
        at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:191)
        at org.springframework.boot.convert.DelimitedStringToCollectionConverter.lambda$convert$0(DelimitedStringToCollectionConverter.java:72)
        at org.springframework.boot.convert.DelimitedStringToCollectionConverter$$Lambda$513/1107588916.apply(Unknown Source)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.util.stream.SpinedBuffer.forEach(SpinedBuffer.java:246)
        at java.util.stream.SpinedBuffer.toString(SpinedBuffer.java:269)
        at java.lang.String.valueOf(String.java:2994)
        at java.lang.StringBuilder.append(StringBuilder.java:131)
        at com.oracle.svm.core.amd64.AMD64CPUFeatureAccess.verifyHostSupportsArchitecture(AMD64CPUFeatureAccess.java:179)
        at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:129)
        at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:186)
        at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

        at com.oracle.svm.core.util.UserError.abort(UserError.java:75)
        at com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:223)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:737)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:526)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:444)
        at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances of org.springframework.util.unit.DataSize are allowed in the image heap as this class should be initialized at image runtime.Object has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked.
Detailed message:
Trace:  object org.springframework.util.unit.DataUnit
        method org.springframework.util.unit.DataSize.determineDataUnit(String, DataUnit)
Call path from entry point to org.springframework.util.unit.DataSize.determineDataUnit(String, DataUnit): 
        at org.springframework.util.unit.DataSize.determineDataUnit(DataSize.java:192)
        at org.springframework.util.unit.DataSize.parse(DataSize.java:182)
        at org.springframework.boot.convert.StringToDataSizeConverter.convert(StringToDataSizeConverter.java:57)
        at org.springframework.boot.convert.StringToDataSizeConverter.convert(StringToDataSizeConverter.java:48)
        at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:41)
        at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:191)
        at org.springframework.boot.convert.DelimitedStringToCollectionConverter.lambda$convert$0(DelimitedStringToCollectionConverter.java:72)
        at org.springframework.boot.convert.DelimitedStringToCollectionConverter$$Lambda$513/1107588916.apply(Unknown Source)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.util.stream.SpinedBuffer.forEach(SpinedBuffer.java:246)
        at java.util.stream.SpinedBuffer.toString(SpinedBuffer.java:269)
        at java.lang.String.valueOf(String.java:2994)
        at java.lang.StringBuilder.append(StringBuilder.java:131)
        at com.oracle.svm.core.amd64.AMD64CPUFeatureAccess.verifyHostSupportsArchitecture(AMD64CPUFeatureAccess.java:179)
        at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:129)
        at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:186)
        at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

        at com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:130)
        at com.oracle.graal.pointsto.BigBang.finish(BigBang.java:565)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:688)
        ... 7 more
Error: Image build request failed with exit status 1

```
![image](https://user-images.githubusercontent.com/20402016/68922884-3014b480-07c0-11ea-9d84-257d56acc582.png)

![image](https://user-images.githubusercontent.com/20402016/68923333-69015900-07c1-11ea-9cdb-f8367efe86b4.png)

**Comment by jkbbwr** [comment]
Also having this issue.

**Comment by aclement** [comment]
This message `No instances of org.springframework.util.unit.DataSize are allowed in the image heap as this class should be initialized at image runtime.Object has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked.` usually indicates you haven't built the feature.  In the compile.sh you will see a reference to the nearby built feature jar. You must jump into the feature and do a quick `mvn clean package` then the compile.sh script will find it.

**Comment by emont01** [comment]
I am experiencing the same issue with GraalVM 19.3.0, but everything works fine with GraalVM 19.2.1, the project I am using webflux-netty (sample) for testing

```bash
Error: No instances of java.net.Inet4Address are allowed in the image heap as this class should be initialized at image runtime. Object has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked.
Trace:  object java.net.InetSocketAddress$InetSocketAddressHolder
        object java.net.InetSocketAddress
        object io.netty.bootstrap.ServerBootstrap
        object reactor.netty.tcp.TcpServerBind
        method reactor.netty.tcp.TcpServer.create()
Call path from entry point to reactor.netty.tcp.TcpServer.create():
        no path found from entry point to target method

Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances of java.net.Inet6Address are allowed in the image heap as this class should be initialized at image runtime. Object has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked.
Trace:
        at parsing reactor.netty.tcp.TcpUtils._updatePort(TcpUtils.java:84)
Call path from entry point to reactor.netty.tcp.TcpUtils._updatePort(SocketAddress, int):
        at reactor.netty.tcp.TcpUtils._updatePort(TcpUtils.java:83)
        at reactor.netty.tcp.TcpUtils.updatePort(TcpUtils.java:75)
        at reactor.netty.tcp.TcpClient.lambda$port$5(TcpClient.java:394)
        at reactor.netty.tcp.TcpClient$$Lambda$560/0x0000000841239440.apply(Unknown Source)
        at sun.security.ec.XECParameters$1.get(XECParameters.java:183)
        at com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:188)
        at com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:141)
        at com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:339)
        at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_ARRAY:Ljava_lang_System_2_0002egetProperty_00028Ljava_lang_String_2_00029Ljava_lang_String_2(generated:0)

com.oracle.svm.core.util.UserError$UserException: Unsupported features in 2 methods
Detailed message:
Error: No instances of java.net.Inet4Address are allowed in the image heap as this class should be initialized at image runtime. Object has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked.
Trace:  object java.net.InetSocketAddress$InetSocketAddressHolder
        object java.net.InetSocketAddress
        object io.netty.bootstrap.ServerBootstrap
        object reactor.netty.tcp.TcpServerBind
        method reactor.netty.tcp.TcpServer.create()
Call path from entry point to reactor.netty.tcp.TcpServer.create():
        no path found from entry point to target method

Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances of java.net.Inet6Address are allowed in the image heap as this class should be initialized at image runtime. Object has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked.
Trace:
        at parsing reactor.netty.tcp.TcpUtils._updatePort(TcpUtils.java:84)
Call path from entry point to reactor.netty.tcp.TcpUtils._updatePort(SocketAddress, int):
        at reactor.netty.tcp.TcpUtils._updatePort(TcpUtils.java:83)
        at reactor.netty.tcp.TcpUtils.updatePort(TcpUtils.java:75)
        at reactor.netty.tcp.TcpClient.lambda$port$5(TcpClient.java:394)
        at reactor.netty.tcp.TcpClient$$Lambda$560/0x0000000841239440.apply(Unknown Source)
        at sun.security.ec.XECParameters$1.get(XECParameters.java:183)
        at com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:188)
        at com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:141)
        at com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:339)
        at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_ARRAY:Ljava_lang_System_2_0002egetProperty_00028Ljava_lang_String_2_00029Ljava_lang_String_2(generated:0)

        at com.oracle.svm.core.util.UserError.abort(UserError.java:75)
        at com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:221)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:736)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:530)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:445)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Unsupported features in 2 methods
Detailed message:
Error: No instances of java.net.Inet4Address are allowed in the image heap as this class should be initialized at image runtime. Object has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked.
Trace:  object java.net.InetSocketAddress$InetSocketAddressHolder
        object java.net.InetSocketAddress
        object io.netty.bootstrap.ServerBootstrap
        object reactor.netty.tcp.TcpServerBind
        method reactor.netty.tcp.TcpServer.create()
Call path from entry point to reactor.netty.tcp.TcpServer.create():
        no path found from entry point to target method

Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances of java.net.Inet6Address are allowed in the image heap as this class should be initialized at image runtime. Object has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked.
Trace:
        at parsing reactor.netty.tcp.TcpUtils._updatePort(TcpUtils.java:84)
Call path from entry point to reactor.netty.tcp.TcpUtils._updatePort(SocketAddress, int):
        at reactor.netty.tcp.TcpUtils._updatePort(TcpUtils.java:83)
        at reactor.netty.tcp.TcpUtils.updatePort(TcpUtils.java:75)
        at reactor.netty.tcp.TcpClient.lambda$port$5(TcpClient.java:394)
        at reactor.netty.tcp.TcpClient$$Lambda$560/0x0000000841239440.apply(Unknown Source)
        at sun.security.ec.XECParameters$1.get(XECParameters.java:183)
        at com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:188)
        at com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:141)
        at com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:339)
        at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_ARRAY:Ljava_lang_System_2_0002egetProperty_00028Ljava_lang_String_2_00029Ljava_lang_String_2(generated:0)

        at com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:129)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:733)
        ... 8 more
Error: Image build request failed with exit status 1
FAILURE: an error occurred when compiling the native-image.
```

**Comment by aclement** [comment]
Yeah, the feature doesn't work with Graal 19.3, indeed. It does work with Graal master if you build your own graal, and so should be fine with 19.3.1 when that comes long (I've been helping get all the blocking issues resolved in graal).  If you do want to work with a dev version of graal, there is an upgrade_19_3 branch of the feature that works with it. That branch will likely become master for the feature when 19.3.1 arrives.

**Comment by emont01** [comment]
Thanks for your reply @aclement !
I am able to download both mx and graal source and compile but I am having problems with the instalation of native-image, when I try to run `gu install native-image` the following error is displayed:
```bash
Downloading: Component catalog from www.graalvm.org
Error: Unsupported Graal VM version: 20.0.0-dev, platform linux/amd64
```

**Comment by aclement** [comment]
If you are building graal, you can just ask it to build native-image for you too. This is the command I was using: `mx --env svm build` run in the vm folder, I think that builds it (as well as the rest of graal).

That doesn't build the agent though, that is more complicated `mx --dynamicimports /substratevm --disable-libpolyglot --disable-polyglot --force-bash-launchers=true --skip-libraries=jvmcicompiler build`

**Comment by emont01** [comment]
I have executed the following command to build graal `mx --env ce-complete build`
I am no expert but based on the content of the corresponding files [1] and [2] I think the one I used should include everything, still after running it the native-image command is not available.

I will try using `--env svm`

[1]
```bash mx.vm/svm
DYNAMIC_IMPORTS=/substratevm
FORCE_BASH_LAUNCHERS=true
SKIP_LIBRARIES=true
```

[2]
```bash mx.vm/ce-complete
DYNAMIC_IMPORTS=/substratevm,/tools,/sulong,/graal-nodejs,truffleruby,graalpython
DISABLE_INSTALLABLES=true
EXCLUDE_COMPONENTS=nju,nic
```

**Comment by emont01** [comment]
@aclement indeed `mx --env svm build` is compiling and now I am able to run `native-image --version` without issues, thanks!

**Comment by emont01** [comment]
@aclement not sure if I should create a new issue, but I am still having problems compiling the examples even after downloading the latest code in graalvm (and building it) and using the source in branch `upgrade_19_3`

GraalVM version is: 
```bash
openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment (build 11.0.5+10-jvmci-19.3-b05-LTS)
OpenJDK 64-Bit Server VM GraalVM LIBGRAAL 20.0.0-dev (build 11.0.5+10-jvmci-19.3-b05-LTS, mixed mode, sharing)
```

Example source is up to date:
```bash
commit 8c819c0fd2493d0ebedddca7cde0372930ed7495 (spring/upgrade_19_3, origin/upgrade_19_3)
Author: Andy Clement <aclement@pivotal.io>
Date:   Fri Dec 13 17:01:28 2019 -0800

    add init config to allow mvc sample to succeed
```

Error running build.sh
```bash
~/spring-graal-native/spring-graal-native-samples/commandlinerunner$ ./build.sh
=== Building commandlinerunner sample ===
Packaging commandlinerunner with Maven
Unpacking commandlinerunner-0.0.1-SNAPSHOT.jar
Compiling commandlinerunner with GraalVM Version dev
Warning: Ignoring server-mode native-image argument --no-server.
SUCCESS
Testing commandlinerunner output
RSS memory: .9M
Image size: 32.8M
FAILURE: the output of the application does not contain the expected output
./test.sh: line 33: kill: (12086) - No such process
```

This is the content of test-output.txt
```bash

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                        

Dec 16, 2019 2:43:41 PM org.springframework.boot.StartupInfoLogger logStarting
INFO: Starting CommandlinerunnerApplication on DESKTOP-JOVQ2LP with PID 12086 (/mnt/c/icte/dev/spring-graal-native/spring-graal-native-samples/commandlinerunner/target/commandlinerunner started by icteadmin in /mnt/c/icte/dev/spring-graal-native/spring-graal-native-samples/commandlinerunner)
Dec 16, 2019 2:43:41 PM org.springframework.boot.SpringApplication logStartupProfileInfo
INFO: No active profile set, falling back to default profiles: default
Dec 16, 2019 2:43:41 PM org.springframework.context.support.AbstractApplicationContext refresh
WARNING: Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.boot.autoconfigure.AutoConfigurationPackages': Unsatisfied dependency expressed through constructor parameter 0: Could not convert argument value of type [[Ljava.lang.String;] to required type [[Ljava.lang.String;]: Failed to convert value of type 'java.lang.String[]' to required type 'java.lang.String[]'; nested exception is java.lang.IllegalArgumentException: Class java.io.Serializable[] is instantiated reflectively but was never registered. Register the class by using org.graalvm.nativeimage.hosted.RuntimeReflection
Dec 16, 2019 2:43:41 PM org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener logMessage
INFO: 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
Dec 16, 2019 2:43:41 PM org.springframework.boot.SpringApplication reportFailure
SEVERE: Application run failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.boot.autoconfigure.AutoConfigurationPackages': Unsatisfied dependency expressed through constructor parameter 0: Could not convert argument value of type [[Ljava.lang.String;] to required type [[Ljava.lang.String;]: Failed to convert value of type 'java.lang.String[]' to required type 'java.lang.String[]'; nested exception is java.lang.IllegalArgumentException: Class java.io.Serializable[] is instantiated reflectively but was never registered. Register the class by using org.graalvm.nativeimage.hosted.RuntimeReflection
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:755)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:226)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1358)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1204)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:879)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at com.example.commandlinerunner.CommandlinerunnerApplication.main(CommandlinerunnerApplication.java:10)
```

**Comment by aclement** [comment]
I have started seeing that one this morning, guess some graal commit has disturbed things. i've fixed it locally but have quite a few changes locally so haven't managed to commit the fix yet. You can fix it yourself by adding the types it is complaining about (java.lang.String[] here) to the reflect.json in the feature.

**Comment by aclement** [comment]
I pushed the fixes related to `java.lang.String[]` and other array types. It is due to a recent graal change where they less aggressively add array types so that moves the job to us.  I've done enough for the samples to work, I haven't defined a general scheme yet.

**Comment by sdeleuze** [comment]
I have tested, it works as expected in `upgrade_19_3` branch about to be merged in `master`.
