### ISSUE TITLE
Error occurred while native image building

### ISSUE THREAD

**Issue by igor-drozdov-n26** [spring-projects-experimental/spring-graal-native#11]
**I'm facing error during building native image.**

Here is Dockerfile which I used (Current latest version is 19.3.0)
```
FROM oracle/graalvm-ce:latest

RUN gu install native-image
RUN yum install git -y
RUN git clone https://github.com/spring-projects-experimental/spring-graal-native.git
WORKDIR spring-graal-native
RUN ./mvnw clean package
RUN git clone --single-branch --branch postgres-r2dbc https://github.com/sausageRoll/kotlindemo.git
WORKDIR /spring-graal-native/spring-graal-native-samples/kotlin-webmvc
RUN ../../mvnw clean install
RUN printf "Unpacking $JAR"
RUN rm -rf unpack
RUN mkdir unpack
WORKDIR /spring-graal-native/spring-graal-native-samples/kotlin-webmvc/unpack
RUN jar -xvf ../target/kotlin-webmvc-0.0.1-SNAPSHOT.jar >/dev/null 2>&1
RUN cp -R META-INF BOOT-INF/classes
WORKDIR /spring-graal-native/spring-graal-native-samples/kotlin-webmvc/unpack/BOOT-INF/classes
RUN LIBPATH=$(find ../../BOOT-INF/lib | tr '\n' ':') && \
    echo $LIBPATH && \
    CP=.:$LIBPATH && \
    echo $CP && \
    CP=$CP:../../../../../spring-graal-native-feature/target/spring-graal-native-feature-0.6.0.BUILD-SNAPSHOT.jar && \
    echo $CP && \
    echo "Compile" && \
    native-image \
      --no-server \
      -H:+TraceClassInitialization \
      -H:Name=kotlindemo \
      -H:+ReportExceptionStackTraces \
      --no-fallback \
      --allow-incomplete-classpath \
      --report-unsupported-elements-at-runtime \
      -DremoveUnusedAutoconfig=true \
      -cp $CP com.example.demo.DemoApplicationKt 
```

All steps are just copied appropriately from compile.sh 
And get the error below:

```
Fatal error: java.lang.RuntimeException: java.lang.RuntimeException: host C compiler or linker does not seem to work: java.lang.RuntimeException: returned 1

Running command: cc -v -o /spring-graal-native/spring-graal-native-samples/kotlin-webmvc/unpack/BOOT-INF/classes/kotlindemo -z noexecstack -Wl,--gc-sections -Wl,--dynamic-list -Wl,/tmp/SVM-2757203419255951332/exported_symbols.list -Wl,-x -L/tmp/SVM-2757203419255951332 -L/opt/graalvm-ce-java8-19.3.0/jre/lib -L/opt/graalvm-ce-java8-19.3.0/jre/lib/svm/clibraries/linux-amd64 /tmp/SVM-2757203419255951332/kotlindemo.o /opt/graalvm-ce-java8-19.3.0/jre/lib/svm/clibraries/linux-amd64/libffi.a /opt/graalvm-ce-java8-19.3.0/jre/lib/svm/clibraries/linux-amd64/liblibchelper.a /opt/graalvm-ce-java8-19.3.0/jre/lib/svm/clibraries/linux-amd64/libjvm.a /opt/graalvm-ce-java8-19.3.0/jre/lib/svm/clibraries/linux-amd64/libstrictmath.a /opt/graalvm-ce-java8-19.3.0/jre/lib/libnet.a /opt/graalvm-ce-java8-19.3.0/jre/lib/libzip.a /opt/graalvm-ce-java8-19.3.0/jre/lib/libjava.a /opt/graalvm-ce-java8-19.3.0/jre/lib/libnio.a -lm -lpthread -ldl -lpthread -lz -lrt

Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-39.0.1) (GCC) 
COMPILER_PATH=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/:/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/:/usr/libexec/gcc/x86_64-redhat-linux/:/usr/lib/gcc/x86_64-redhat-linux/4.8.5/:/usr/lib/gcc/x86_64-redhat-linux/
LIBRARY_PATH=/usr/lib/gcc/x86_64-redhat-linux/4.8.5/:/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/:/lib/../lib64/:/usr/lib/../lib64/:/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-v' '-o' '/spring-graal-native/spring-graal-native-samples/kotlin-webmvc/unpack/BOOT-INF/classes/kotlindemo' '-z' 'noexecstack' '-L/tmp/SVM-2757203419255951332' '-L/opt/graalvm-ce-java8-19.3.0/jre/lib' '-L/opt/graalvm-ce-java8-19.3.0/jre/lib/svm/clibraries/linux-amd64' '-mtune=generic' '-march=x86-64'
 /usr/libexec/gcc/x86_64-redhat-linux/4.8.5/collect2 --build-id --no-add-needed --eh-frame-hdr --hash-style=gnu -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o /spring-graal-native/spring-graal-native-samples/kotlin-webmvc/unpack/BOOT-INF/classes/kotlindemo -z noexecstack /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/crt1.o /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/crti.o /usr/lib/gcc/x86_64-redhat-linux/4.8.5/crtbegin.o -L/tmp/SVM-2757203419255951332 -L/opt/graalvm-ce-java8-19.3.0/jre/lib -L/opt/graalvm-ce-java8-19.3.0/jre/lib/svm/clibraries/linux-amd64 -L/usr/lib/gcc/x86_64-redhat-linux/4.8.5 -L/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../.. --gc-sections --dynamic-list /tmp/SVM-2757203419255951332/exported_symbols.list -x /tmp/SVM-2757203419255951332/kotlindemo.o /opt/graalvm-ce-java8-19.3.0/jre/lib/svm/clibraries/linux-amd64/libffi.a /opt/graalvm-ce-java8-19.3.0/jre/lib/svm/clibraries/linux-amd64/liblibchelper.a /opt/graalvm-ce-java8-19.3.0/jre/lib/svm/clibraries/linux-amd64/libjvm.a /opt/graalvm-ce-java8-19.3.0/jre/lib/svm/clibraries/linux-amd64/libstrictmath.a /opt/graalvm-ce-java8-19.3.0/jre/lib/libnet.a /opt/graalvm-ce-java8-19.3.0/jre/lib/libzip.a /opt/graalvm-ce-java8-19.3.0/jre/lib/libjava.a /opt/graalvm-ce-java8-19.3.0/jre/lib/libnio.a -lm -lpthread -ldl -lpthread -lz -lrt -lgcc --as-needed -lgcc_s --no-as-needed -lc -lgcc --as-needed -lgcc_s --no-as-needed /usr/lib/gcc/x86_64-redhat-linux/4.8.5/crtend.o /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/crtn.o
/tmp/SVM-2757203419255951332/kotlindemo.o:(.data+0x2c0): undefined reference to `Java_sun_misc_Unsafe_defineClass'
/opt/graalvm-ce-java8-19.3.0/jre/lib/libjava.a(Throwable.o): In function `Java_java_lang_Throwable_fillInStackTrace':
/opt/jprt/T/P1/225159.buildslave/s/jdk/src/share/native/java/lang/Throwable.c:49: undefined reference to `JVM_FillInStackTrace'
/opt/graalvm-ce-java8-19.3.0/jre/lib/libjava.a(URLClassPath.o): In function `Java_sun_misc_URLClassPath_getLookupCacheForClassLoader':
/opt/jprt/T/P1/225159.buildslave/s/jdk/src/share/native/sun/misc/URLClassPath.c:100: undefined reference to `JVM_GetResourceLookupCache'
/opt/graalvm-ce-java8-19.3.0/jre/lib/libjava.a(URLClassPath.o): In function `Java_sun_misc_URLClassPath_getLookupCacheURLs':
/opt/jprt/T/P1/225159.buildslave/s/jdk/src/share/native/sun/misc/URLClassPath.c:77: undefined reference to `JVM_GetResourceLookupCacheURLs'
/opt/graalvm-ce-java8-19.3.0/jre/lib/libjava.a(VM.o): In function `Java_sun_misc_VM_latestUserDefinedLoader0':
/opt/jprt/T/P1/225159.buildslave/s/jdk/src/share/native/sun/misc/VM.c:116: undefined reference to `JVM_LatestUserDefinedLoader'
collect2: error: ld returned 1 exit status

        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
        at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
        at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:462)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:315)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:454)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:115)
Caused by: java.lang.RuntimeException: host C compiler or linker does not seem to work: java.lang.RuntimeException: returned 1

Running command: cc -v -o /spring-graal-native/spring-graal-native-samples/kotlin-webmvc/unpack/BOOT-INF/classes/kotlindemo -z noexecstack -Wl,--gc-sections -Wl,--dynamic-list -Wl,/tmp/SVM-2757203419255951332/exported_symbols.list -Wl,-x -L/tmp/SVM-2757203419255951332 -L/opt/graalvm-ce-java8-19.3.0/jre/lib -L/opt/graalvm-ce-java8-19.3.0/jre/lib/svm/clibraries/linux-amd64 /tmp/SVM-2757203419255951332/kotlindemo.o /opt/graalvm-ce-java8-19.3.0/jre/lib/svm/clibraries/linux-amd64/libffi.a /opt/graalvm-ce-java8-19.3.0/jre/lib/svm/clibraries/linux-amd64/liblibchelper.a /opt/graalvm-ce-java8-19.3.0/jre/lib/svm/clibraries/linux-amd64/libjvm.a /opt/graalvm-ce-java8-19.3.0/jre/lib/svm/clibraries/linux-amd64/libstrictmath.a /opt/graalvm-ce-java8-19.3.0/jre/lib/libnet.a /opt/graalvm-ce-java8-19.3.0/jre/lib/libzip.a /opt/graalvm-ce-java8-19.3.0/jre/lib/libjava.a /opt/graalvm-ce-java8-19.3.0/jre/lib/libnio.a -lm -lpthread -ldl -lpthread -lz -lrt

Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-39.0.1) (GCC) 
COMPILER_PATH=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/:/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/:/usr/libexec/gcc/x86_64-redhat-linux/:/usr/lib/gcc/x86_64-redhat-linux/4.8.5/:/usr/lib/gcc/x86_64-redhat-linux/
LIBRARY_PATH=/usr/lib/gcc/x86_64-redhat-linux/4.8.5/:/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/:/lib/../lib64/:/usr/lib/../lib64/:/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-v' '-o' '/spring-graal-native/spring-graal-native-samples/kotlin-webmvc/unpack/BOOT-INF/classes/kotlindemo' '-z' 'noexecstack' '-L/tmp/SVM-2757203419255951332' '-L/opt/graalvm-ce-java8-19.3.0/jre/lib' '-L/opt/graalvm-ce-java8-19.3.0/jre/lib/svm/clibraries/linux-amd64' '-mtune=generic' '-march=x86-64'
 /usr/libexec/gcc/x86_64-redhat-linux/4.8.5/collect2 --build-id --no-add-needed --eh-frame-hdr --hash-style=gnu -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o /spring-graal-native/spring-graal-native-samples/kotlin-webmvc/unpack/BOOT-INF/classes/kotlindemo -z noexecstack /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/crt1.o /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/crti.o /usr/lib/gcc/x86_64-redhat-linux/4.8.5/crtbegin.o -L/tmp/SVM-2757203419255951332 -L/opt/graalvm-ce-java8-19.3.0/jre/lib -L/opt/graalvm-ce-java8-19.3.0/jre/lib/svm/clibraries/linux-amd64 -L/usr/lib/gcc/x86_64-redhat-linux/4.8.5 -L/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../.. --gc-sections --dynamic-list /tmp/SVM-2757203419255951332/exported_symbols.list -x /tmp/SVM-2757203419255951332/kotlindemo.o /opt/graalvm-ce-java8-19.3.0/jre/lib/svm/clibraries/linux-amd64/libffi.a /opt/graalvm-ce-java8-19.3.0/jre/lib/svm/clibraries/linux-amd64/liblibchelper.a /opt/graalvm-ce-java8-19.3.0/jre/lib/svm/clibraries/linux-amd64/libjvm.a /opt/graalvm-ce-java8-19.3.0/jre/lib/svm/clibraries/linux-amd64/libstrictmath.a /opt/graalvm-ce-java8-19.3.0/jre/lib/libnet.a /opt/graalvm-ce-java8-19.3.0/jre/lib/libzip.a /opt/graalvm-ce-java8-19.3.0/jre/lib/libjava.a /opt/graalvm-ce-java8-19.3.0/jre/lib/libnio.a -lm -lpthread -ldl -lpthread -lz -lrt -lgcc --as-needed -lgcc_s --no-as-needed -lc -lgcc --as-needed -lgcc_s --no-as-needed /usr/lib/gcc/x86_64-redhat-linux/4.8.5/crtend.o /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/crtn.o
/tmp/SVM-2757203419255951332/kotlindemo.o:(.data+0x2c0): undefined reference to `Java_sun_misc_Unsafe_defineClass'
/opt/graalvm-ce-java8-19.3.0/jre/lib/libjava.a(Throwable.o): In function `Java_java_lang_Throwable_fillInStackTrace':
/opt/jprt/T/P1/225159.buildslave/s/jdk/src/share/native/java/lang/Throwable.c:49: undefined reference to `JVM_FillInStackTrace'
/opt/graalvm-ce-java8-19.3.0/jre/lib/libjava.a(URLClassPath.o): In function `Java_sun_misc_URLClassPath_getLookupCacheForClassLoader':
/opt/jprt/T/P1/225159.buildslave/s/jdk/src/share/native/sun/misc/URLClassPath.c:100: undefined reference to `JVM_GetResourceLookupCache'
/opt/graalvm-ce-java8-19.3.0/jre/lib/libjava.a(URLClassPath.o): In function `Java_sun_misc_URLClassPath_getLookupCacheURLs':
/opt/jprt/T/P1/225159.buildslave/s/jdk/src/share/native/sun/misc/URLClassPath.c:77: undefined reference to `JVM_GetResourceLookupCacheURLs'
/opt/graalvm-ce-java8-19.3.0/jre/lib/libjava.a(VM.o): In function `Java_sun_misc_VM_latestUserDefinedLoader0':
/opt/jprt/T/P1/225159.buildslave/s/jdk/src/share/native/sun/misc/VM.c:116: undefined reference to `JVM_LatestUserDefinedLoader'
collect2: error: ld returned 1 exit status

        at com.oracle.svm.hosted.image.NativeBootImageViaCC.write(NativeBootImageViaCC.java:382)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:652)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:445)
        at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

```

**Comment by aclement** [comment]
The upgrade to use 19.3 is non trivial (working on it right now). 19.2 works better with master branch right now.   I encountered something similar to you and raised https://github.com/oracle/graal/issues/1920 against the graal project. Have you tried both flavours of graal 19.3? 8 and 11? I found when one didn't work, the other might...

**Comment by igor-drozdov-n26** [comment]
Graal 19.2.1 and 19.2.0.1 works well with demo applications from spring-graal-native-samples
