### ISSUE TITLE
Error occurred while native image building springmvc-tomcat

### ISSUE THREAD

**Issue by Anand0583** [spring-projects-experimental/spring-graal-native#12]
When executing the compile.sh of springmvc-tomcat. Native image is not getting generated. 

Can you please let me know what needs to be done.

Receiving the following error.
`Fatal error: java.lang.NoClassDefFoundError: org/springframework/orm/jpa/JpaVendorAdapter
        at java.base/java.lang.Class.getDeclaringClass0(Native Method)
        at java.base/java.lang.Class.isMemberClass(Class.java:1668)
        at java.base/sun.reflect.annotation.TypeAnnotationParser.buildAnnotatedTypes(TypeAnnotationParser.java:134)
        at java.base/java.lang.reflect.Executable.getAnnotatedParameterTypes(Executable.java:700)
        at com.oracle.svm.reflect.target.Target_java_lang_reflect_Executable$AnnotatedParameterTypesComputer.compute(Target_java_lang_reflect_Executable.java:154)
        at com.oracle.svm.hosted.substitute.ComputedValueField.readValue(ComputedValueField.java:265)
        at com.oracle.svm.core.meta.ReadableJavaField.readFieldValue(ReadableJavaField.java:35)
        at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readValue(AnalysisConstantReflectionProvider.java:98)
        at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readFieldValue(AnalysisConstantReflectionProvider.java:77)
        at com.oracle.graal.pointsto.ObjectScanner.scanField(ObjectScanner.java:175)
        at com.oracle.graal.pointsto.ObjectScanner.doScan(ObjectScanner.java:344)
        at com.oracle.graal.pointsto.ObjectScanner.access$400(ObjectScanner.java:62)
        at com.oracle.graal.pointsto.ObjectScanner$3$1.run(ObjectScanner.java:414)
        at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:171)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Error: Image build request failed with exit status 1
`

**Comment by Anand0583** [comment]
@sdeleuze what do you need from me.

**Comment by Anand0583** [comment]
Please correct the samples. So we can understand what needs to be done for graalvm support for spring boot services.

**Comment by sdeleuze** [comment]
I have just check that `springmvc-tomcat` on `upgrade_19_3` branch (about to merged in `master`) works as expected with GraalVM 19.3.1 (broken on Mac but we will provide shortly compatbible GraalVM builds with the required fixes). Sorry for the lag.
