### ISSUE TITLE
Scan error in Spring Feature, trying to find missing jar

### ISSUE THREAD

**Issue by gostaDrivekitt** [spring-projects-experimental/spring-graal-native#35]
Trying to build a pretty small app using Spring Boot 2.2.0 using GRPC libraries.

It's trying to find 
`grpc-core-1.21.0.jar` 
in the 
`/repository/io/grpc/grpc-netty-shaded/1.21.0/` 
directory. 

```
[clr:84473]    classlist:  21,846.86 ms
 ____             _               _____          _
/ ___| _ __  _ __(_)_ __   __ _  |  ___|__  __ _| |_ _   _ _ __ ___
\___ \| '_ \| '__| | '_ \ / _` | | |_ / _ \/ _` | __| | | | '__/ _ \
 ___) | |_) | |  | | | | | (_| | |  _|  __/ (_| | |_| |_| | | |  __/
|____/| .__/|_|  |_|_| |_|\__, | |_|  \___|\__,_|\__|\__,_|_|  \___|
      |_|                 |___/

Use -Dverbose=true on native-image call to see more detailed information from the feature
Remove unused config = false
[clr:84473]        (cap):   1,717.82 ms
Found #397 types in static list to register
Skipping #52 types not on the classpath
Attempting proxy registration of #23 proxies
Skipped registration of #4 proxies - relevant types not on classpath
[clr:84473]        setup:   3,737.12 ms
Fatal error: java.lang.RuntimeException: java.lang.RuntimeException: Problem during scan of /Users/gostajonasson/.m2/repository/io/grpc/grpc-netty-shaded/1.21.0/grpc-core-1.21.0.jar
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:461)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:310)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:448)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:113)
Caused by: java.lang.RuntimeException: Problem during scan of /Users/gostajonasson/.m2/repository/io/grpc/grpc-netty-shaded/1.21.0/grpc-core-1.21.0.jar
	at org.springframework.graal.type.TypeSystem.indexJar(TypeSystem.java:275)
	at org.springframework.graal.type.TypeSystem.index(TypeSystem.java:228)
	at org.springframework.graal.type.TypeSystem.<init>(TypeSystem.java:73)
	at org.springframework.graal.type.TypeSystem.get(TypeSystem.java:68)
	at org.springframework.graal.support.ResourcesHandler.register(ResourcesHandler.java:86)
	at org.springframework.graal.support.SpringFeature.beforeAnalysis(SpringFeature.java:84)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$7(NativeImageGenerator.java:670)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:63)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:670)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:526)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:444)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.io.FileNotFoundException: /Users/gostajonasson/.m2/repository/io/grpc/grpc-netty-shaded/1.21.0/grpc-core-1.21.0.jar (No such file or directory)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at org.springframework.graal.type.TypeSystem.indexJar(TypeSystem.java:261)
	... 15 more
Error: Image build request failed with exit status 1
```

**Comment by gostaDrivekitt** [comment]
The dependency tree looks like this, that is probably the issue:
<img width="636" alt="Screen Shot 2019-12-20 at 14 51 24" src="https://user-images.githubusercontent.com/38914904/71259269-59cd7800-2338-11ea-8f01-403dd3860fc1.png">

**Comment by gostaDrivekitt** [comment]
👍
