### ISSUE TITLE
No @CompilationHint found for: ManagementContextConfigurationImportSelector

### ISSUE THREAD

**Issue by gostaDrivekitt** [spring-projects-experimental/spring-graal-native#36]
Running with the latest self compiled version of **spring-graal-native-feature** from the master branch (0.6.0.BUILD-SNAPSHOT) on a rather small Spring Boot app that I have.

Then I get this error:
```
Fatal error: java.lang.IllegalStateException: java.lang.IllegalStateException: No @CompilationHint found for import selector: org.springframework.boot.actuate.autoconfigure.web.server.ManagementContextConfigurationImportSelector
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:461)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:310)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:448)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:113)
Caused by: java.lang.IllegalStateException: No @CompilationHint found for import selector: org.springframework.boot.actuate.autoconfigure.web.server.ManagementContextConfigurationImportSelector
	at org.springframework.graal.type.Type.getHints(Type.java:865)
```

What do I need to do in order to compile successfully?

**Comment by gostaDrivekitt** [comment]
Closing this since it's a duplicate of https://github.com/spring-projects-experimental/spring-graal-native/issues/9

I'd still be happy to get help fixing the issue 😃
