### ISSUE TITLE
Fix vanilla-orm sample

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-graal-native#41]
Running `vanilla-orm` in `upgrade_19_3` branch currently fails with the following error:

```
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
Jan 20, 2020 1:57:07 PM org.springframework.boot.SpringApplication reportFailure
SEVERE: Application run failed
java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:787)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:768)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at app.main.SampleApplication.main(SampleApplication.java:38)
Caused by: javax.persistence.TransactionRequiredException: No EntityManager with actual transaction available for current thread - cannot reliably process 'persist' call
	at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:298)
	at com.sun.proxy.$Proxy229.persist(Unknown Source)
	at app.main.Bootstrap.run(SampleApplication.java:55)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:784)
	... 5 more
```

Notice that `vanilla-orm2` works, and the main difference between the 2 seems to be the fact that `vanilla-orm` uses `@Transactional` while `vanilla-orm2` uses programmatic transactions. Surprisingly, `spring-petclinic-jpa` works even if it uses `@Transactional`.

**Comment by aclement** [comment]
Fixed when we addressed the vanilla-tx sample!
