### ISSUE TITLE
No @CompilationHint found for import selector

### ISSUE THREAD

**Issue by mbarbeaux** [spring-projects-experimental/spring-graal-native#59]
Hi,

So today I updated my Spring Feature clone repo and tried native compiling my Spring boot project with the recent changes of the master branch. But it seems I'm missing something (it worked perfecty with the lastest master version before merging of branch extensible-configuration).

I'm getting an error at native compiling :

```
Fatal error: java.lang.IllegalStateException: java.lang.IllegalStateException: No @CompilationHint found for import selector: org.springframework.boot.autoconfigure.cache.CacheAutoConfiguration$CacheConfigurationImportSelector
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
        at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
        at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:462)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:357)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:501)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:115)
Caused by: java.lang.IllegalStateException: No @CompilationHint found for import selector: org.springframework.boot.autoconfigure.cache.CacheAutoConfiguration$CacheConfigurationImportSelector
        at org.springframework.graal.type.Type.getHints(Type.java:1074)
        at org.springframework.graal.support.ResourcesHandler.processType(ResourcesHandler.java:728)
        at org.springframework.graal.support.ResourcesHandler.processType(ResourcesHandler.java:1030)
        at org.springframework.graal.support.ResourcesHandler.processType(ResourcesHandler.java:633)
        at org.springframework.graal.support.ResourcesHandler.checkAndRegisterConfigurationType(ResourcesHandler.java:621)
        at org.springframework.graal.support.ResourcesHandler.processSpringFactory(ResourcesHandler.java:564)
        at org.springframework.graal.support.ResourcesHandler.processSpringFactories(ResourcesHandler.java:425)
        at org.springframework.graal.support.ResourcesHandler.register(ResourcesHandler.java:110)
        at org.springframework.graal.support.SpringFeature.beforeAnalysis(SpringFeature.java:79)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$7(NativeImageGenerator.java:674)
        at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:63)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:674)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:530)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:445)
        at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

Strange behaviour since I'm not using any cache library or functionality in my project. 
My project uses resource bundles, jackson, has some basic @Component beans without any database configuration, caching system nor web server controller. 
I set spring.main.web-application-type to none and only have spring-boot-starter and spring-boot-starter-json (excluding spring-boot-starter-web) as dependencies.

Any idea where I should start looking for to fix this ?

**Comment by aclement** [comment]
I think that is because the recent changes now require two dependencies to be added. The feature itself and then the configuration project for your version of spring (currently there is only one, but there is a plan to have multiple).  So you need to add the dependency on:
```
<dependency>
  <groupId>org.springframework.experimental</groupId>
  <artifactId>spring-graal-native-configuration</artifactId>
  <version>0.6.0.BUILD-SNAPSHOT</version>
</dependency>
```

There is some new wiki content on using the feature here:
[https://github.com/spring-projects-experimental/spring-graal-native/wiki/Feature](https://github.com/spring-projects-experimental/spring-graal-native/wiki/Feature)

Do let me know if that helps.

**Comment by mbarbeaux** [comment]
You were right, I missed the new dependency in my pom.
Sorry for the inconvenience !

**Comment by fabri1983** [comment]
Thanks. This helped me to solve same issue. However it seems the mentioned missing dependency `spring-graal-native-configuration` is not defined in the _Feature_ wiki as a needed dependency. Should it be added? Or am I confusing things?
Thanks again.

**Comment by sdeleuze** [comment]
We have made changes in order to prepare `0.6.0.RELEASE`, so the wiki is right you should used `spring-graal-native` artifact that contains the 3 others. Some options names have changed so check the documentation it is up to date.
