### ISSUE TITLE
Fix and improve guides

### ISSUE THREAD

**Issue by celcius112** [spring-projects-experimental/spring-graal-native#81]
Hello everyone,

By following the [feature example](https://repo.spring.io/milestone/org/springframework/experimental/spring-graal-native-docs/0.6.0.RELEASE/spring-graal-native-docs-0.6.0.RELEASE.zip!/reference/index.html#feature) I end up with a 
```
java.lang.ClassNotFoundException: org.apache.tomcat.websocket.server.WsContextListener
	at org.springframework.boot.web.embedded.tomcat.TomcatEmbeddedWebappClassLoader.loadClass(TomcatEmbeddedWebappClassLoader.java:72)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1188)
	at org.apache.catalina.core.DefaultInstanceManager.loadClass(DefaultInstanceManager.java:540)
	at org.apache.catalina.core.DefaultInstanceManager.loadClassMaybePrivileged(DefaultInstanceManager.java:521)
	at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:150)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4612)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5151)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374)
```
I'm using Spring Boot 2.3.0.M4 with spring-graal-native 0.6.0.RELEASE. The problem arises with 20.0.0.r8-grl and 20.0.0.r11-grl on MacOS.

I'll try with the agent and hybrid solutions to see if the same problem arises.

If you need more information, like a sample project, please let me know, but it is exactly the same code as described in the example.

**Comment by celcius112** [comment]
Edit: the hybrid approach works fine

**Comment by sdeleuze** [comment]
Good catch, sorry we missed that one, we will release `0.6.1.RELEASE` shortly with a fix.

You can make the guide working by adding an exclusion for Tomcat WebSocket support like that:

```xml
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-web</artifactId>
	<exclusions>
		<exclusion>
			<groupId>org.apache.tomcat.embed</groupId>
			<artifactId>tomcat-embed-websocket</artifactId>
		</exclusion>
	</exclusions>
</dependency>
```

That said, I tend to think it would be nice to fix the feature to allow it to work without this exclusion that we have also in the `springmvc-tomat` sample. @aclement @fhanik Do you think it could be doable?

**Comment by celcius112** [comment]
Thank you for your response @sdeleuze. 

Small question, are there plans to have automated tests capabilities in Spring for that kind of situation ?

**Comment by sdeleuze** [comment]
We have [automated integration tests run on CI for each commit](https://ci.spring.io/teams/spring-graal-native/pipelines/spring-graal-native), and also an effort to run [a subset of Spring Framework unit tests](https://github.com/spring-projects-experimental/spring-graal-native/issues/22).

We could use asciidoctor capabilities to display code snippets from real projects to avoid this kind of issue, I have created related gh-82 issue for 0.7 milestone.

**Comment by celcius112** [comment]
pretty neat 👌 thank you for your answers

**Comment by fhanik** [comment]
The simplest work around at the moment is to just craft another `reflection.json` file and include it with your command line. We're still fine tuning the Tomcat needs and are also working directly with the Apache Tomcat community to get this included in the project itself.

https://github.com/apache/tomcat/pull/274
