### ISSUE TITLE
Error: Classes that should be initialized at run time got initialized during image building

### ISSUE THREAD

**Issue by MuriloFtto** [spring-projects-experimental/spring-graal-native#95]
Hello, I'm having a problem with some classes that should be initialized at build time, in relation to the proxy, any suggestions?

Grail Version: 20.0.0
Spring version: 0.6.0.RELEASE

thank in advance for your attention :D

**Stack** 

`Error: Classes that should be initialized at run time got initialized during image building:
 org.springframework.context.ApplicationContext the class was requested to be initialized at build time (from the command line). com.sun.proxy.$Proxy382 caused initialization of this class with the following trace: 
	at org.springframework.context.ApplicationContext.<clinit>(ApplicationContext.java)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.sun.proxy.$Proxy382.<clinit>(Unknown Source)

org.springframework.context.annotation.ImportAware the class was requested to be initialized at build time (from the command line). com.sun.proxy.$Proxy384 caused initialization of this class with the following trace: 
	at org.springframework.context.annotation.ImportAware.<clinit>(ImportAware.java)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.sun.proxy.$Proxy384.<clinit>(Unknown Source)

br.com.sysmo.server.dto.DocumentoEletronicoDTO was unintentionally initialized at build time. com.sun.proxy.$Proxy367 caused initialization of this class with the following trace: 
	at br.com.sysmo.server.dto.DocumentoEletronicoDTO.<clinit>(DocumentoEletronicoDTO.java)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.sun.proxy.$Proxy367.<clinit>(Unknown Source)

org.springframework.security.config.annotation.web.WebSecurityConfigurer the class was requested to be initialized at build time (from the command line). com.sun.proxy.$Proxy386 caused initialization of this class with the following trace: 
	at org.springframework.security.config.annotation.web.WebSecurityConfigurer.<clinit>(WebSecurityConfigurer.java)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.sun.proxy.$Proxy386.<clinit>(Unknown Source)

br.com.sysmo.server.dto.DocumentoEletronicoCancelamentoDTO the class was requested to be initialized at build time (from the command line). com.sun.proxy.$Proxy368 caused initialization of this class with the following trace: 
	at br.com.sysmo.server.dto.DocumentoEletronicoCancelamentoDTO.<clinit>(DocumentoEletronicoCancelamentoDTO.java)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.sun.proxy.$Proxy368.<clinit>(Unknown Source)

org.springframework.context.annotation.ConfigurationClassEnhancer$EnhancedConfiguration was unintentionally initialized at build time. com.sun.proxy.$Proxy384 caused initialization of this class with the following trace: 
	at org.springframework.context.annotation.ConfigurationClassEnhancer$EnhancedConfiguration.<clinit>(ConfigurationClassEnhancer.java)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.sun.proxy.$Proxy384.<clinit>(Unknown Source)

org.springframework.core.io.ResourceLoader was unintentionally initialized at build time. com.sun.proxy.$Proxy383 caused initialization of this class with the following trace: 
	at org.springframework.core.io.ResourceLoader.<clinit>(ResourceLoader.java)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.sun.proxy.$Proxy383.<clinit>(Unknown Source)

org.springframework.core.type.AnnotationMetadata the class was requested to be initialized at build time (from the command line). com.sun.proxy.$Proxy384 caused initialization of this class with the following trace: 
	at org.springframework.core.type.AnnotationMetadata.<clinit>(AnnotationMetadata.java)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.sun.proxy.$Proxy384.<clinit>(Unknown Source)

org.springframework.beans.factory.BeanFactory the class was requested to be initialized at build time (from the command line). com.sun.proxy.$Proxy384 caused initialization of this class with the following trace: 
	at org.springframework.beans.factory.BeanFactory.<clinit>(BeanFactory.java)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.sun.proxy.$Proxy384.<clinit>(Unknown Source)

br.com.sysmo.server.dto.venda.EmitenteDTO was unintentionally initialized at build time. com.sun.proxy.$Proxy370 caused initialization of this class with the following trace: 
	at br.com.sysmo.server.dto.venda.EmitenteDTO.<clinit>(EmitenteDTO.java)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.sun.proxy.$Proxy370.<clinit>(Unknown Source)

org.springframework.context.ApplicationContextAware the class was requested to be initialized at build time (from the command line). com.sun.proxy.$Proxy382 caused initialization of this class with the following trace: 
	at org.springframework.context.ApplicationContextAware.<clinit>(ApplicationContextAware.java)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.sun.proxy.$Proxy382.<clinit>(Unknown Source)

br.com.sysmo.s1.server.documento.eletronico.service.DocumentoEletronicoCancelamentoService the class was requested to be initialized at build time (from the command line). com.sun.proxy.$Proxy368 caused initialization of this class with the following trace: 
	at br.com.sysmo.s1.server.documento.eletronico.service.DocumentoEletronicoCancelamentoService.<clinit>(DocumentoEletronicoCancelamentoService.java)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.sun.proxy.$Proxy368.<clinit>(Unknown Source)

org.springframework.web.context.ServletContextAware the class was requested to be initialized at build time (from the command line). com.sun.proxy.$Proxy382 caused initialization of this class with the following trace: 
	at org.springframework.web.context.ServletContextAware.<clinit>(ServletContextAware.java)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.sun.proxy.$Proxy382.<clinit>(Unknown Source)

javax.servlet.ServletContext was unintentionally initialized at build time. com.sun.proxy.$Proxy382 caused initialization of this class with the following trace: 
	at javax.servlet.ServletContext.<clinit>(ServletContext.java)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.sun.proxy.$Proxy382.<clinit>(Unknown Source)

br.com.sysmo.s1.server.documento.eletronico.service.DocumentoEletronicoNumeroDOCService was unintentionally initialized at build time. com.sun.proxy.$Proxy369 caused initialization of this class with the following trace: 
	at br.com.sysmo.s1.server.documento.eletronico.service.DocumentoEletronicoNumeroDOCService.<clinit>(DocumentoEletronicoNumeroDOCService.java)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.sun.proxy.$Proxy369.<clinit>(Unknown Source)

br.com.sysmo.s1.server.documento.eletronico.service.DocumentoEletronicoStatusSefazService was unintentionally initialized at build time. com.sun.proxy.$Proxy370 caused initialization of this class with the following trace: 
	at br.com.sysmo.s1.server.documento.eletronico.service.DocumentoEletronicoStatusSefazService.<clinit>(DocumentoEletronicoStatusSefazService.java)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.sun.proxy.$Proxy370.<clinit>(Unknown Source)

br.com.sysmo.s1.server.documento.eletronico.service.ConfiguracaoDocumentoEletronicoService was unintentionally initialized at build time. com.sun.proxy.$Proxy366 caused initialization of this class with the following trace: 
	at br.com.sysmo.s1.server.documento.eletronico.service.ConfiguracaoDocumentoEletronicoService.<clinit>(ConfiguracaoDocumentoEletronicoService.java)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.sun.proxy.$Proxy366.<clinit>(Unknown Source)

org.postgresql.Driver the class was requested to be initialized at build time (from the command line). org.h2.Driver caused initialization of this class with the following trace: 
	at org.postgresql.Driver.<clinit>(Driver.java)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at java.sql.DriverManager$2.run(DriverManager.java:603)
	at java.sql.DriverManager$2.run(DriverManager.java:583)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.sql.DriverManager.loadInitialDrivers(DriverManager.java:583)
	at java.sql.DriverManager.<clinit>(DriverManager.java:101)
	at org.h2.Driver.load(Driver.java:155)
	at org.h2.Driver.<clinit>(Driver.java:41)

org.springframework.context.ResourceLoaderAware was unintentionally initialized at build time. com.sun.proxy.$Proxy383 caused initialization of this class with the following trace: 
	at org.springframework.context.ResourceLoaderAware.<clinit>(ResourceLoaderAware.java)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.sun.proxy.$Proxy383.<clinit>(Unknown Source)

br.com.sysmo.s1.server.documento.eletronico.service.DocumentoEletronicoAutorizacaoService the class was requested to be initialized at build time (from the command line). com.sun.proxy.$Proxy367 caused initialization of this class with the following trace: 
	at br.com.sysmo.s1.server.documento.eletronico.service.DocumentoEletronicoAutorizacaoService.<clinit>(DocumentoEletronicoAutorizacaoService.java)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.sun.proxy.$Proxy367.<clinit>(Unknown Source)

org.springframework.security.config.annotation.SecurityBuilder the class was requested to be initialized at build time (from the command line). com.sun.proxy.$Proxy386 caused initialization of this class with the following trace: 
	at org.springframework.security.config.annotation.SecurityBuilder.<clinit>(SecurityBuilder.java)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.sun.proxy.$Proxy386.<clinit>(Unknown Source)

org.springframework.beans.factory.BeanClassLoaderAware the class was requested to be initialized at build time (from the command line). com.sun.proxy.$Proxy385 caused initialization of this class with the following trace: 
	at org.springframework.beans.factory.BeanClassLoaderAware.<clinit>(BeanClassLoaderAware.java)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.sun.proxy.$Proxy385.<clinit>(Unknown Source)`

**Comment by aclement** [comment]
Couple of things:
- I see `org.springframework.context.annotation.ConfigurationClassEnhancer$EnhancedConfiguration` referenced in there. Have you definitely switched off CGLIB proxies by adopting the `proxyBeanMethods=false` option on configuration?  (per https://repo.spring.io/snapshot/org/springframework/experimental/spring-graal-native-docs/0.6.0.BUILD-SNAPSHOT/spring-graal-native-docs-0.6.0.BUILD-SNAPSHOT.zip!/reference/index.html#_proxies )

- I would try pushing some of those types to build time init and see if that helps.  Modify the `buildArgs` in your build script to include the necessary `--initialize-at-build-time=br.com.sysmo.s1.server.documento.eletronico.service.DocumentoEletronicoAutorizacaoService`. You can comma list entries or include that argument multiple times.

**Comment by MuriloFtto** [comment]
@aclement, Thank you, your suggestions were well taken.
