### ISSUE TITLE
Could not find default constructor for AnnotationConfigServletWebServerApplicationContext

### ISSUE THREAD

**Issue by sapessi** [spring-projects-experimental/spring-graal-native#96]
I'm working on supporting native image build for [Serverless Java Container](https://github.com/awslabs/aws-serverless-java-container). I have the application building correctly with our embedded container. 

You can see the [sample application in the `graalvm` branch of the project](https://github.com/awslabs/aws-serverless-java-container/tree/graalvm/samples/springboot2/native-pet-store).

When I start the executable inside AWS Lambda I get the following exception:

```
:: Spring Boot ::                        
Apr 13, 2020 4:24:26 PM org.springframework.boot.SpringApplication reportFailure
SEVERE: Application run failed
org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext]: No default constructor found; nested exception is java.lang.NoSuchMethodException: org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext.<init>()
at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:146)
at org.springframework.boot.SpringApplication.createApplicationContext(SpringApplication.java:588)
at org.springframework.boot.SpringApplication.run(SpringApplication.java:311)
at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:140)
at com.amazonaws.serverless.proxy.spring.SpringBootLambdaContainerHandler.initialize(SpringBootLambdaContainerHandler.java:195)
at com.amazonaws.serverless.proxy.InitializationWrapper.start(InitializationWrapper.java:35)
at com.amazonaws.serverless.proxy.spring.SpringBootProxyHandlerBuilder.buildAndInitialize(SpringBootProxyHandlerBuilder.java:81)
at com.amazonaws.serverless.proxy.spring.SpringBootLambdaContainerHandler.getAwsProxyHandler(SpringBootLambdaContainerHandler.java:93)
at com.amazonaws.serverless.runtime.Runtime.<init>(Runtime.java:27)
at com.amazonaws.serverless.runtime.Runtime.<init>(Runtime.java:22)
at com.amazonaws.serverless.sample.springboot2.Application.main(Application.java:52)
Caused by: java.lang.NoSuchMethodException: org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext.<init>()
at java.lang.Class.getConstructor0(DynamicHub.java:3082)
at java.lang.Class.getDeclaredConstructor(DynamicHub.java:2178)
at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:139)
... 10 more
```

**Comment by aclement** [comment]
A very quick few to proceed (not saying this is the fix, it just will get you moving) - quickly create a `META-INF/native-image` directory on the build classpath (maybe in src/main/resources). In that native-image folder create a file `reflect-config.json` and add:
```
[
{"name":"org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext","allDeclaredConstructors":true}
]
```

If that simply uncovers a wall of these, consider a run with the agent if you can, to try and catch them all: https://repo.spring.io/snapshot/org/springframework/experimental/spring-graal-native-docs/0.6.0.BUILD-SNAPSHOT/spring-graal-native-docs-0.6.0.BUILD-SNAPSHOT.zip!/reference/index.html#hybrid (not sure how easy that is for you).

**Comment by sapessi** [comment]
Thanks for the tip @aclement - I'll keep digging and update here when I have a solution (or a new wall).

**Comment by aclement** [comment]
Noting here that we do have a hint that exposes `AnnotationConfigServletWebServerApplicationContext` but the trigger is whether `WebMvcAutoConfiguration` is active. That suggests this trigger isn't quite right/broad-enough to catch all apps that need it.

**Comment by sapessi** [comment]
Update. The rabbit hole was deep. In the end, I changed the build process to [execute the JAR application with the Java agent](https://github.com/awslabs/aws-serverless-java-container/blob/graalvm/samples/springboot2/native-pet-store/scripts/graalvm-build.sh#L15-L16) as you suggested. I updated the main file to [look for a text execution property and exercise a method in the controller](https://github.com/awslabs/aws-serverless-java-container/blob/graalvm/samples/springboot2/native-pet-store/src/main/java/com/amazonaws/serverless/sample/springboot2/Application.java#L24-L32).

Looks really good! Twitter thread here: https://twitter.com/sapessi/status/1249917053684682752
